export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_REQUEST_SUCCESS = "FETCH_USER_REQUEST_SUCCESS";
export const FETCH_USER_REQUEST_ERROR = "FETCH_USER_REQUEST_ERROR";

export const SELECT_BUSINESS_PROFILE = "SELECT_BUSINESS_PROFILE";
export const DESELECT_BUSINESS_PROFILE = "DESELECT_BUSINESS_PROFILE";
