export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_REQUEST_SUCCESS = "GET_USER_REQUEST_SUCCESS";
export const GET_USER_REQUEST_ERROR = "GET_USER_REQUEST_ERROR";

export const SELECT_BUSINESS_PROFILE = "SELECT_BUSINESS_PROFILE";
export const DESELECT_BUSINESS_PROFILE = "DESELECT_BUSINESS_PROFILE";

export const GET_PARTNERS_REQUEST = "GET_PARTNERS_REQUEST";
export const GET_PARTNERS_SUCCESS = "GET_PARTNERS_SUCCESS";
export const GET_PARTNERS_ERROR = "GET_PARTNERS_ERROR";

export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
